export const ADD_EQUIPO = "ADD_EQUIPO";
export const BORRAR_EQUIPO = "BORRAR_EQUIPO";

export const CONECTAR_ENLACE = "CONECTAR_ENLACE";
export const BORRAR_ENLACE = "BORRAR_ENLACE";

export const ADD_DATO = "ADD_DATO";
export const CAMBIAR_DATO = "CAMBIAR_DATO";
export const BORRAR_DATO = "BORRAR_DATO";

export const ADD_INCOGNITA = "ADD_INCOGNITA";
export const BORRAR_INCOGNITA = "BORRAR_INCOGNITA";
export const CAMBIAR_VALOR_INICIAL = "CAMBIAR_VALOR_INICIAL";

export const ADD_ECUACION = "ADD_ECUACION";
export const BORRAR_ECUACION = "BORRAR_ECUACION";

export const ADD_RELACION = "ADD_RELACION";
export const BORRAR_RELACION = "BORRAR_RELACION";

export const CAMBIAR_SELECCION = "CAMBIAR_SELECCION";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
